sonar.projectKey=cybervault
sonar.projectName=CyberVault SDEMS
sonar.projectVersion=1.0

# Source directories
sonar.sources=backend/app,frontend/src

# Test directories
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**/*

# Python specifics
sonar.python.version=3.11

# Exclusions
sonar.exclusions=backend/venv/**/*,frontend/node_modules/**/*,**/__pycache__/**/*,backend/evidence_storage/**/*,backend/cybervault.db

# Javascript specifics
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
